#!/stage1/sh
export _PATH="$PATH"
export PATH="/stage1"

set -x

cd /
rm /init
EXEC=/init

exec >>/boot.txt 2>&1

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t ext4 /dev/block/mmcblk0p15 /cache

#busybox date segfaults? so yeah.
busybox cat /sys/devices/platform/s3c2410-rtc/rtc/rtc1/date
busybox cat /sys/devices/platform/s3c2410-rtc/rtc/rtc1/time

image=/stage1/boot.cpio

if test -e /cache/.rebooting ; then

	rm -rf /cache/.rebooting

	# disable lpm
	echo 0 > /sys/class/power_supply/battery/charging_mode_booting
fi

if test -e /cache/.startrecovery || grep -q bootmode=2 /proc/cmdline ; then
	# recovery boot so dd param.lfs to work around missing proprietary driver
	bzcat /stage1/param.bz2 | dd of=/dev/block/mmcblk0p9

	rm -rf /cache/.startrecovery
	image=/stage1/recovery.cpio

	# disable lpm
	echo 0 > /sys/class/power_supply/battery/charging_mode_booting
fi

umount /cache
rm -rf /cache

cpio -i < ${image}

busybox cat /sys/class/power_supply/battery/charging_mode_booting

if test $(busybox cat /sys/class/power_supply/battery/charging_mode_booting) == 1 ; then
	# low power mode
	cp -f lpm.rc init.venturi.rc
fi

umount /sys
umount /proc

mount -t vfat /dev/block/mmcblk0p17 /emmc
busybox cat /boot.txt >> /emmc/boot.txt
umount /emmc

rm -rf /dev/* /stage1 /emmc

export PATH="${_PATH}"

exec $EXEC
