#!/stage1/sh
export _PATH="$PATH"
export PATH="/stage1"

set -x

cd /
rm /init

date >>/boot.txt
exec >>/boot.txt 2>&1

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t ext4 /dev/block/mmcblk0p15 /cache

image=/stage1/boot.cpio

if test -e /cache/.startrecovery || grep -q bootmode=2 /proc/cmdline ; then
	# recovery boot so dd param.lfs to work around missing proprietary driver
	bzcat /stage1/param.bz2 | dd of=/dev/block/mmcblk0p9

	rm -rf /cache/.startrecovery
	image=/stage1/recovery.cpio

	# disable lpm
	echo 0 > /sys/class/power_supply/battery/charging_mode_booting
fi

umount /cache
rm -rf /cache

cpio -i < ${image}

if grep -q 1 /sys/class/power_supply/battery/charging_mode_booting ; then
	# low power mode
	cp -f lpm.rc init.rc
fi

umount /sys
umount /proc

date >> /boot.txt

mount -t vfat /dev/block/mmcblk0p17 /emmc
cp /boot.txt /emmc/boot.txt
umount /emmc

rm -rf /dev/* /stage1 /emmc

export PATH="${_PATH}"

exec /init
